Trying to resolve threading issue on Nexus 5 where Gist Sync doesn't kick you back.
    java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'Thread-16616'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {430f3f10} called on null, FYI main Looper is Looper (main, tid 1) {430f3f10})
            at android.webkit.WebView.checkThread(WebView.java:2073)
            at android.webkit.WebView.stopLoading(WebView.java:932)
            at com.dappervision.wearscript.BackgroundService.reset(BackgroundService.java:262)



Signed-off-by: Mike DiGiovanni <vinblau@gmail.com>